plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories { mavenCentral() }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

javafx {
    version = "25"
    modules = [ 'javafx.controls', 'javafx.swing' ]
}


dependencies {
    implementation "org.controlsfx:controlsfx:11.2.3"

    implementation "com.twelvemonkeys.imageio:imageio-core:3.13.0"
    implementation "com.twelvemonkeys.imageio:imageio-jpeg:3.13.0"
    implementation "com.twelvemonkeys.imageio:imageio-bmp:3.13.0"
    implementation "com.twelvemonkeys.imageio:imageio-tiff:3.13.0"

    implementation "net.coobird:thumbnailator:0.4.21"
}

application {
    mainClass = "com.tensorupscaler.App"
}
